# Generated by Django 3.0 on 2019-12-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='角色')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('permission', models.ManyToManyField(to='rbac.Permission', verbose_name='权限')),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
    ]
