# Generated by Django 3.0 on 2019-12-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20191219_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(default='name', max_length=150, verbose_name='姓名'),
        ),
    ]
