# Generated by Django 3.0 on 2019-12-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20191219_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态'),
        ),
    ]
