# Generated by Django 3.0 on 2020-01-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0012_permission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态'),
        ),
    ]
